---
- name: Deploy Spring Boot App from S3 to EC2 (Ubuntu)
  hosts: webservers
  become: yes

  vars:
    app_dir: /opt/app
    jar_name: ""
    s3_bucket: ""
    aws_region: "us-east-1"

  tasks:
    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Install Java 17 (OpenJDK)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    # - name: Install AWS CLI
    #   apt:
    #     name: awscli
    #     state: present
    #     update_cache: yes

    - name: Download JAR from S3
      shell: aws s3 cp s3://{{ s3_bucket }}/{{ jar_name }} {{ app_dir }}/{{ jar_name }} --region {{ aws_region }}
      args:
        executable: /bin/bash
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"


    - name: Kill running Spring Boot app if exists
      shell: pkill -f "{{ jar_name }}"
      ignore_errors: yes

    - name: Start Spring Boot app on port 8081
      shell: nohup java -jar {{ app_dir }}/{{ jar_name }} --server.port=8081 > {{ app_dir }}/app.log 2>&1 &
      async: 0
      poll: 0

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure nginx as reverse proxy
      copy:
        dest: /etc/nginx/sites-available/springboot
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8081/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Enable nginx config
      file:
        src: /etc/nginx/sites-available/springboot
        dest: /etc/nginx/sites-enabled/springboot
        state: link
        force: yes

    - name: Remove default nginx config if exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
        force: yes

    - name: Reload nginx to apply new config
      service:
        name: nginx
        state: restarted
        enabled: yes
