---
- hosts: ec2
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jre
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8081;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
      notify: Reload Nginx

    - name: Download jar from S3
      shell: aws s3 cp s3://testingbucketforjenkins12345/spring-boot-2-hello-world-1.0.2-SNAPSHOT.jar /home/ubuntu/app.jar

    - name: Kill old app
      shell: pkill -f 'java -jar' || true

    - name: Run the Spring Boot app
      shell: nohup java -jar /home/ubuntu/app.jar --server.port=8081 > /home/ubuntu/app.log 2>&1 &
      args:
        chdir: /home/ubuntu/

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
